# Unique project key
sonar.projectKey=catalogue

# Project name
sonar.projectName=roboshop-catalogue

# Project version
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# NodeJS test reports (optional)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude node_modules
sonar.exclusions=node_modules/**

# SonarQube server URL
sonar.host.url=http://98.92.214.40:9000

# Authentication token (recommended)
sonar.login=sqa_cd90d53418736c4d8e1b019b5f918844e11a36bc